# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_observer/api/types/config.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dev_observer/api/types/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dev_observer.api.types import observations_pb2 as dev__observer_dot_api_dot_types_dot_observations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#dev_observer/api/types/config.proto\x12\x1d\x64\x65v_observer.api.types.config\x1a)dev_observer/api/types/observations.proto\"O\n\x0cGlobalConfig\x12?\n\x08\x61nalysis\x18\x01 \x01(\x0b\x32-.dev_observer.api.types.config.AnalysisConfig\"W\n\x0e\x41nalysisConfig\x12\x45\n\x0erepo_analyzers\x18\x01 \x03(\x0b\x32-.dev_observer.api.types.observations.Analyzerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_observer.api.types.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLOBALCONFIG']._serialized_start=113
  _globals['_GLOBALCONFIG']._serialized_end=192
  _globals['_ANALYSISCONFIG']._serialized_start=194
  _globals['_ANALYSISCONFIG']._serialized_end=281
# @@protoc_insertion_point(module_scope)
