// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.28.3
// source: dev_observer/api/types/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Analyzer } from "./observations";

export const protobufPackage = "dev_observer.api.types.config";

export interface GlobalConfig {
  analysis: AnalysisConfig | undefined;
}

export interface AnalysisConfig {
  repoAnalyzers: Analyzer[];
  siteAnalyzers: Analyzer[];
}

export interface UserManagementStatus {
  enabled: boolean;
  publicApiKey?: string | undefined;
}

function createBaseGlobalConfig(): GlobalConfig {
  return { analysis: undefined };
}

export const GlobalConfig: MessageFns<GlobalConfig> = {
  encode(message: GlobalConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.analysis !== undefined) {
      AnalysisConfig.encode(message.analysis, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GlobalConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGlobalConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.analysis = AnalysisConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GlobalConfig {
    return { analysis: isSet(object.analysis) ? AnalysisConfig.fromJSON(object.analysis) : undefined };
  },

  toJSON(message: GlobalConfig): unknown {
    const obj: any = {};
    if (message.analysis !== undefined) {
      obj.analysis = AnalysisConfig.toJSON(message.analysis);
    }
    return obj;
  },

  create(base?: DeepPartial<GlobalConfig>): GlobalConfig {
    return GlobalConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GlobalConfig>): GlobalConfig {
    const message = createBaseGlobalConfig();
    message.analysis = (object.analysis !== undefined && object.analysis !== null)
      ? AnalysisConfig.fromPartial(object.analysis)
      : undefined;
    return message;
  },
};

function createBaseAnalysisConfig(): AnalysisConfig {
  return { repoAnalyzers: [], siteAnalyzers: [] };
}

export const AnalysisConfig: MessageFns<AnalysisConfig> = {
  encode(message: AnalysisConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.repoAnalyzers) {
      Analyzer.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.siteAnalyzers) {
      Analyzer.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnalysisConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnalysisConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.repoAnalyzers.push(Analyzer.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.siteAnalyzers.push(Analyzer.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnalysisConfig {
    return {
      repoAnalyzers: gt.Array.isArray(object?.repoAnalyzers)
        ? object.repoAnalyzers.map((e: any) => Analyzer.fromJSON(e))
        : [],
      siteAnalyzers: gt.Array.isArray(object?.siteAnalyzers)
        ? object.siteAnalyzers.map((e: any) => Analyzer.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AnalysisConfig): unknown {
    const obj: any = {};
    if (message.repoAnalyzers?.length) {
      obj.repoAnalyzers = message.repoAnalyzers.map((e) => Analyzer.toJSON(e));
    }
    if (message.siteAnalyzers?.length) {
      obj.siteAnalyzers = message.siteAnalyzers.map((e) => Analyzer.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<AnalysisConfig>): AnalysisConfig {
    return AnalysisConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AnalysisConfig>): AnalysisConfig {
    const message = createBaseAnalysisConfig();
    message.repoAnalyzers = object.repoAnalyzers?.map((e) => Analyzer.fromPartial(e)) || [];
    message.siteAnalyzers = object.siteAnalyzers?.map((e) => Analyzer.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUserManagementStatus(): UserManagementStatus {
  return { enabled: false, publicApiKey: undefined };
}

export const UserManagementStatus: MessageFns<UserManagementStatus> = {
  encode(message: UserManagementStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.publicApiKey !== undefined) {
      writer.uint32(18).string(message.publicApiKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserManagementStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserManagementStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.publicApiKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserManagementStatus {
    return {
      enabled: isSet(object.enabled) ? gt.Boolean(object.enabled) : false,
      publicApiKey: isSet(object.publicApiKey) ? gt.String(object.publicApiKey) : undefined,
    };
  },

  toJSON(message: UserManagementStatus): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.publicApiKey !== undefined) {
      obj.publicApiKey = message.publicApiKey;
    }
    return obj;
  },

  create(base?: DeepPartial<UserManagementStatus>): UserManagementStatus {
    return UserManagementStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UserManagementStatus>): UserManagementStatus {
    const message = createBaseUserManagementStatus();
    message.enabled = object.enabled ?? false;
    message.publicApiKey = object.publicApiKey ?? undefined;
    return message;
  },
};

declare const self: any | undefined;
declare const window: any | undefined;
declare const global: any | undefined;
const gt: any = (() => {
  if (typeof globalThis !== "undefined") {
    return globalThis;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  throw "Unable to locate global object";
})();

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
