# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_observer/api/web/change_analysis.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dev_observer/api/web/change_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from dev_observer.api.types import observations_pb2 as dev__observer_dot_api_dot_types_dot_observations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*dev_observer/api/web/change_analysis.proto\x12$dev_observer.api.web.change_analysis\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)dev_observer/api/types/observations.proto\"*\n\x17\x45nrollRepositoryRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\"<\n\x18\x45nrollRepositoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x19UnenrollRepositoryRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\">\n\x1aUnenrollRepositoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xe1\x01\n\x19GetChangeSummariesRequest\x12\x14\n\x07repo_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x33\n\nstart_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12\x31\n\x08\x65nd_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x02\x88\x01\x01\x12\x13\n\x06status\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\n\n\x08_repo_idB\r\n\x0b_start_dateB\x0b\n\t_end_dateB\t\n\x07_status\"\xa7\x02\n\rChangeSummary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07repo_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12J\n\x0bobservation\x18\x04 \x01(\x0b\x32\x30.dev_observer.api.types.observations.ObservationH\x00\x88\x01\x01\x12\x1a\n\rerror_message\x18\x05 \x01(\tH\x01\x88\x01\x01\x12/\n\x0b\x61nalyzed_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0e\n\x0c_observationB\x10\n\x0e_error_message\"d\n\x1aGetChangeSummariesResponse\x12\x46\n\tsummaries\x18\x01 \x03(\x0b\x32\x33.dev_observer.api.web.change_analysis.ChangeSummary\"7\n$GetRepositoryEnrollmentStatusRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\"\x83\x01\n%GetRepositoryEnrollmentStatusResponse\x12\x10\n\x08\x65nrolled\x18\x01 \x01(\x08\x12\x36\n\rlast_analysis\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x42\x10\n\x0e_last_analysisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_observer.api.web.change_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENROLLREPOSITORYREQUEST']._serialized_start=160
  _globals['_ENROLLREPOSITORYREQUEST']._serialized_end=202
  _globals['_ENROLLREPOSITORYRESPONSE']._serialized_start=204
  _globals['_ENROLLREPOSITORYRESPONSE']._serialized_end=264
  _globals['_UNENROLLREPOSITORYREQUEST']._serialized_start=266
  _globals['_UNENROLLREPOSITORYREQUEST']._serialized_end=310
  _globals['_UNENROLLREPOSITORYRESPONSE']._serialized_start=312
  _globals['_UNENROLLREPOSITORYRESPONSE']._serialized_end=374
  _globals['_GETCHANGESUMMARIESREQUEST']._serialized_start=377
  _globals['_GETCHANGESUMMARIESREQUEST']._serialized_end=602
  _globals['_CHANGESUMMARY']._serialized_start=605
  _globals['_CHANGESUMMARY']._serialized_end=900
  _globals['_GETCHANGESUMMARIESRESPONSE']._serialized_start=902
  _globals['_GETCHANGESUMMARIESRESPONSE']._serialized_end=1002
  _globals['_GETREPOSITORYENROLLMENTSTATUSREQUEST']._serialized_start=1004
  _globals['_GETREPOSITORYENROLLMENTSTATUSREQUEST']._serialized_end=1059
  _globals['_GETREPOSITORYENROLLMENTSTATUSRESPONSE']._serialized_start=1062
  _globals['_GETREPOSITORYENROLLMENTSTATUSRESPONSE']._serialized_end=1193
# @@protoc_insertion_point(module_scope)
