# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_observer/api/web/changes.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dev_observer/api/web/changes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dev_observer.api.types import changes_pb2 as dev__observer_dot_api_dot_types_dot_changes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"dev_observer/api/web/changes.proto\x12\x1c\x64\x65v_observer.api.web.changes\x1a$dev_observer/api/types/changes.proto\"M\n\x1bListChangesSummariesRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"|\n\x1cListChangesSummariesResponse\x12G\n\tsummaries\x18\x01 \x03(\x0b\x32\x34.dev_observer.api.types.changes.GitHubChangesSummary\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\".\n\x18GetChangesSummaryRequest\x12\x12\n\nsummary_id\x18\x01 \x01(\t\"b\n\x19GetChangesSummaryResponse\x12\x45\n\x07summary\x18\x01 \x01(\x0b\x32\x34.dev_observer.api.types.changes.GitHubChangesSummary\"A\n\x1b\x43reateChangesSummaryRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\x12\x11\n\tdays_back\x18\x02 \x01(\x05\"e\n\x1c\x43reateChangesSummaryResponse\x12\x45\n\x07summary\x18\x01 \x01(\x0b\x32\x34.dev_observer.api.types.changes.GitHubChangesSummary\"1\n\x1b\x44\x65leteChangesSummaryRequest\x12\x12\n\nsummary_id\x18\x01 \x01(\t\"/\n\x1c\x44\x65leteChangesSummaryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_observer.api.web.changes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTCHANGESSUMMARIESREQUEST']._serialized_start=106
  _globals['_LISTCHANGESSUMMARIESREQUEST']._serialized_end=183
  _globals['_LISTCHANGESSUMMARIESRESPONSE']._serialized_start=185
  _globals['_LISTCHANGESSUMMARIESRESPONSE']._serialized_end=309
  _globals['_GETCHANGESSUMMARYREQUEST']._serialized_start=311
  _globals['_GETCHANGESSUMMARYREQUEST']._serialized_end=357
  _globals['_GETCHANGESSUMMARYRESPONSE']._serialized_start=359
  _globals['_GETCHANGESSUMMARYRESPONSE']._serialized_end=457
  _globals['_CREATECHANGESSUMMARYREQUEST']._serialized_start=459
  _globals['_CREATECHANGESSUMMARYREQUEST']._serialized_end=524
  _globals['_CREATECHANGESSUMMARYRESPONSE']._serialized_start=526
  _globals['_CREATECHANGESSUMMARYRESPONSE']._serialized_end=627
  _globals['_DELETECHANGESSUMMARYREQUEST']._serialized_start=629
  _globals['_DELETECHANGESSUMMARYREQUEST']._serialized_end=678
  _globals['_DELETECHANGESSUMMARYRESPONSE']._serialized_start=680
  _globals['_DELETECHANGESSUMMARYRESPONSE']._serialized_end=727
# @@protoc_insertion_point(module_scope)
