# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_observer/api/web/repositories.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dev_observer/api/web/repositories.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dev_observer.api.types import repo_pb2 as dev__observer_dot_api_dot_types_dot_repo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'dev_observer/api/web/repositories.proto\x12!dev_observer.api.web.repositories\x1a!dev_observer/api/types/repo.proto\"^\n\x1eListGithubRepositoriesResponse\x12<\n\x05repos\x18\x01 \x03(\x0b\x32-.dev_observer.api.types.repo.GitHubRepository\")\n\x1a\x41\x64\x64GithubRepositoryRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"Z\n\x1b\x41\x64\x64GithubRepositoryResponse\x12;\n\x04repo\x18\x01 \x01(\x0b\x32-.dev_observer.api.types.repo.GitHubRepository\"\x1a\n\x18RescanRepositoryResponse\"T\n\x15GetRepositoryResponse\x12;\n\x04repo\x18\x01 \x01(\x0b\x32-.dev_observer.api.types.repo.GitHubRepository\"X\n\x18\x44\x65leteRepositoryResponse\x12<\n\x05repos\x18\x01 \x03(\x0b\x32-.dev_observer.api.types.repo.GitHubRepository\";\n(EnrollRepositoryForChangeAnalysisRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\"h\n)EnrollRepositoryForChangeAnalysisResponse\x12;\n\x04repo\x18\x01 \x01(\x0b\x32-.dev_observer.api.types.repo.GitHubRepository\">\n+UnenrollRepositoryFromChangeAnalysisRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\"k\n,UnenrollRepositoryFromChangeAnalysisResponse\x12;\n\x04repo\x18\x01 \x01(\x0b\x32-.dev_observer.api.types.repo.GitHubRepository\"\x93\x01\n\x18GetChangeAnalysesRequest\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\x12\x16\n\tdate_from\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x64\x61te_to\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06status\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_date_fromB\n\n\x08_date_toB\t\n\x07_status\"^\n\x19GetChangeAnalysesResponse\x12\x41\n\x08\x61nalyses\x18\x01 \x03(\x0b\x32/.dev_observer.api.types.repo.RepoChangeAnalysis\"/\n\x18GetChangeAnalysisRequest\x12\x13\n\x0b\x61nalysis_id\x18\x01 \x01(\t\"^\n\x19GetChangeAnalysisResponse\x12\x41\n\x08\x61nalysis\x18\x01 \x01(\x0b\x32/.dev_observer.api.types.repo.RepoChangeAnalysisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_observer.api.web.repositories_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTGITHUBREPOSITORIESRESPONSE']._serialized_start=113
  _globals['_LISTGITHUBREPOSITORIESRESPONSE']._serialized_end=207
  _globals['_ADDGITHUBREPOSITORYREQUEST']._serialized_start=209
  _globals['_ADDGITHUBREPOSITORYREQUEST']._serialized_end=250
  _globals['_ADDGITHUBREPOSITORYRESPONSE']._serialized_start=252
  _globals['_ADDGITHUBREPOSITORYRESPONSE']._serialized_end=342
  _globals['_RESCANREPOSITORYRESPONSE']._serialized_start=344
  _globals['_RESCANREPOSITORYRESPONSE']._serialized_end=370
  _globals['_GETREPOSITORYRESPONSE']._serialized_start=372
  _globals['_GETREPOSITORYRESPONSE']._serialized_end=456
  _globals['_DELETEREPOSITORYRESPONSE']._serialized_start=458
  _globals['_DELETEREPOSITORYRESPONSE']._serialized_end=546
  _globals['_ENROLLREPOSITORYFORCHANGEANALYSISREQUEST']._serialized_start=548
  _globals['_ENROLLREPOSITORYFORCHANGEANALYSISREQUEST']._serialized_end=607
  _globals['_ENROLLREPOSITORYFORCHANGEANALYSISRESPONSE']._serialized_start=609
  _globals['_ENROLLREPOSITORYFORCHANGEANALYSISRESPONSE']._serialized_end=713
  _globals['_UNENROLLREPOSITORYFROMCHANGEANALYSISREQUEST']._serialized_start=715
  _globals['_UNENROLLREPOSITORYFROMCHANGEANALYSISREQUEST']._serialized_end=777
  _globals['_UNENROLLREPOSITORYFROMCHANGEANALYSISRESPONSE']._serialized_start=779
  _globals['_UNENROLLREPOSITORYFROMCHANGEANALYSISRESPONSE']._serialized_end=886
  _globals['_GETCHANGEANALYSESREQUEST']._serialized_start=889
  _globals['_GETCHANGEANALYSESREQUEST']._serialized_end=1036
  _globals['_GETCHANGEANALYSESRESPONSE']._serialized_start=1038
  _globals['_GETCHANGEANALYSESRESPONSE']._serialized_end=1132
  _globals['_GETCHANGEANALYSISREQUEST']._serialized_start=1134
  _globals['_GETCHANGEANALYSISREQUEST']._serialized_end=1181
  _globals['_GETCHANGEANALYSISRESPONSE']._serialized_start=1183
  _globals['_GETCHANGEANALYSISRESPONSE']._serialized_end=1277
# @@protoc_insertion_point(module_scope)
