// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.28.3
// source: dev_observer/api/web/repositories.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { GitHubRepository } from "../types/repo";

export const protobufPackage = "dev_observer.api.web.repositories";

export interface ListGithubRepositoriesResponse {
  repos: GitHubRepository[];
}

export interface AddGithubRepositoryRequest {
  url: string;
}

export interface AddGithubRepositoryResponse {
  repo: GitHubRepository | undefined;
}

export interface RescanRepositoryResponse {
}

export interface GetRepositoryResponse {
  repo: GitHubRepository | undefined;
}

export interface DeleteRepositoryResponse {
  repos: GitHubRepository[];
}

function createBaseListGithubRepositoriesResponse(): ListGithubRepositoriesResponse {
  return { repos: [] };
}

export const ListGithubRepositoriesResponse: MessageFns<ListGithubRepositoriesResponse> = {
  encode(message: ListGithubRepositoriesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.repos) {
      GitHubRepository.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListGithubRepositoriesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListGithubRepositoriesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.repos.push(GitHubRepository.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListGithubRepositoriesResponse {
    return {
      repos: globalThis.Array.isArray(object?.repos) ? object.repos.map((e: any) => GitHubRepository.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListGithubRepositoriesResponse): unknown {
    const obj: any = {};
    if (message.repos?.length) {
      obj.repos = message.repos.map((e) => GitHubRepository.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListGithubRepositoriesResponse>): ListGithubRepositoriesResponse {
    return ListGithubRepositoriesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListGithubRepositoriesResponse>): ListGithubRepositoriesResponse {
    const message = createBaseListGithubRepositoriesResponse();
    message.repos = object.repos?.map((e) => GitHubRepository.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddGithubRepositoryRequest(): AddGithubRepositoryRequest {
  return { url: "" };
}

export const AddGithubRepositoryRequest: MessageFns<AddGithubRepositoryRequest> = {
  encode(message: AddGithubRepositoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddGithubRepositoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddGithubRepositoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddGithubRepositoryRequest {
    return { url: isSet(object.url) ? globalThis.String(object.url) : "" };
  },

  toJSON(message: AddGithubRepositoryRequest): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create(base?: DeepPartial<AddGithubRepositoryRequest>): AddGithubRepositoryRequest {
    return AddGithubRepositoryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AddGithubRepositoryRequest>): AddGithubRepositoryRequest {
    const message = createBaseAddGithubRepositoryRequest();
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseAddGithubRepositoryResponse(): AddGithubRepositoryResponse {
  return { repo: undefined };
}

export const AddGithubRepositoryResponse: MessageFns<AddGithubRepositoryResponse> = {
  encode(message: AddGithubRepositoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.repo !== undefined) {
      GitHubRepository.encode(message.repo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddGithubRepositoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddGithubRepositoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.repo = GitHubRepository.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddGithubRepositoryResponse {
    return { repo: isSet(object.repo) ? GitHubRepository.fromJSON(object.repo) : undefined };
  },

  toJSON(message: AddGithubRepositoryResponse): unknown {
    const obj: any = {};
    if (message.repo !== undefined) {
      obj.repo = GitHubRepository.toJSON(message.repo);
    }
    return obj;
  },

  create(base?: DeepPartial<AddGithubRepositoryResponse>): AddGithubRepositoryResponse {
    return AddGithubRepositoryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AddGithubRepositoryResponse>): AddGithubRepositoryResponse {
    const message = createBaseAddGithubRepositoryResponse();
    message.repo = (object.repo !== undefined && object.repo !== null)
      ? GitHubRepository.fromPartial(object.repo)
      : undefined;
    return message;
  },
};

function createBaseRescanRepositoryResponse(): RescanRepositoryResponse {
  return {};
}

export const RescanRepositoryResponse: MessageFns<RescanRepositoryResponse> = {
  encode(_: RescanRepositoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RescanRepositoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRescanRepositoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RescanRepositoryResponse {
    return {};
  },

  toJSON(_: RescanRepositoryResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<RescanRepositoryResponse>): RescanRepositoryResponse {
    return RescanRepositoryResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<RescanRepositoryResponse>): RescanRepositoryResponse {
    const message = createBaseRescanRepositoryResponse();
    return message;
  },
};

function createBaseGetRepositoryResponse(): GetRepositoryResponse {
  return { repo: undefined };
}

export const GetRepositoryResponse: MessageFns<GetRepositoryResponse> = {
  encode(message: GetRepositoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.repo !== undefined) {
      GitHubRepository.encode(message.repo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRepositoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRepositoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.repo = GitHubRepository.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRepositoryResponse {
    return { repo: isSet(object.repo) ? GitHubRepository.fromJSON(object.repo) : undefined };
  },

  toJSON(message: GetRepositoryResponse): unknown {
    const obj: any = {};
    if (message.repo !== undefined) {
      obj.repo = GitHubRepository.toJSON(message.repo);
    }
    return obj;
  },

  create(base?: DeepPartial<GetRepositoryResponse>): GetRepositoryResponse {
    return GetRepositoryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetRepositoryResponse>): GetRepositoryResponse {
    const message = createBaseGetRepositoryResponse();
    message.repo = (object.repo !== undefined && object.repo !== null)
      ? GitHubRepository.fromPartial(object.repo)
      : undefined;
    return message;
  },
};

function createBaseDeleteRepositoryResponse(): DeleteRepositoryResponse {
  return { repos: [] };
}

export const DeleteRepositoryResponse: MessageFns<DeleteRepositoryResponse> = {
  encode(message: DeleteRepositoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.repos) {
      GitHubRepository.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteRepositoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteRepositoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.repos.push(GitHubRepository.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteRepositoryResponse {
    return {
      repos: globalThis.Array.isArray(object?.repos) ? object.repos.map((e: any) => GitHubRepository.fromJSON(e)) : [],
    };
  },

  toJSON(message: DeleteRepositoryResponse): unknown {
    const obj: any = {};
    if (message.repos?.length) {
      obj.repos = message.repos.map((e) => GitHubRepository.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteRepositoryResponse>): DeleteRepositoryResponse {
    return DeleteRepositoryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteRepositoryResponse>): DeleteRepositoryResponse {
    const message = createBaseDeleteRepositoryResponse();
    message.repos = object.repos?.map((e) => GitHubRepository.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
